import "./globals.css";
import { DM_Sans } from "next/font/google";

const dmSans = DM_Sans({ subsets: ["latin"], display: "swap" });

export const metadata = {
  title: "Youssef Hamdi",
  description:
    "My Portfolio to show my Projects and Skills Generated by next.js, tailwindcss and Sanity.io ",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ scrollBehavior: "smooth" }}>
      <body className={dmSans.className}>{children}</body>
    </html>
  );
}
